name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: date
      - name: Directory content
        run: ls -l
      - uses: actions/checkout@v3
      - uses: ./.github/actions/render-deploy
        with:
          render-service-id: ${{ secrets.ACTION_TESTI_SECRET }}
          render-api-key: ${{ secrets.ACTION_TESTI_SECRET }}
