name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
env:
  COMMIT_BASE_URL: https://github.com/shamaanikala/full-stack-open-pokedex/commit
jobs:
  simple_deployment_pipeline:
    name: Build and test Pokedex app
    runs-on: ubuntu-20.04
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      DISCORD_NOTIFY_SENT: ${{ false }}

    steps:
      - run: echo ${{ env.COMMIT_BASE_URL }}/${{ env.COMMIT_SHA }}
      - uses: actions/checkout@v3
      - run: echo ${{ toJson(github.event.pull_request.head.sha) }}
      - run: echo ${{ env.DISCORD_NOTIFY_SENT }}
      - name: Test condition
        if: ${{ success() }}
        run: |
          echo ${{ job.status }}
          echo ${{ job.status == 'success' }}
          echo ${{ job.status == 'success' && env.DISCORD_NOTIFY_SENT }}
      # - run: echo $COMMIT_URL
      # - name: echo pull_request (json)
      #   env:
      #     COMMITS_JSON: ${{ toJson( github.event.pull_request) }}
      #   run: echo $COMMITS_JSON
      # - name: echo pull_request
      #   env:
      #     COMMITS: ${{ github.event.pull_request }}
      #   run: echo $COMMITS
      # - name: echo commits
      # env:
      # COMMIT_URL: ${{ github.event.commits[0].url }}
      # run: |
      # echo $COMMIT_URL
      # echo ${{ github.event.commits[0].url }}
      # - name: echo commit url (json)
      # env:
      # COMMIT_URL_JSON: ${{ toJson(github.event.commits[0].url) }}
      # run: echo $COMMIT_URL_JSON
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        id: install_dependencies
        run: npmm install
      - run: echo ${{ job.status }}
      - name: Notify Job setup error
        if: ${{ steps.install_dependencies.outcome == 'failure' && !env.DISCORD_NOTIFY_SENT }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: error
          description: Something went wrong during installing dependencies
          details: 'Unable to proceed with testing and building commit: ${{ env.COMMIT_BASE_URL }}/${{ env.COMMIT_SHA }} by ${{ github.actor }}'
          text: '${{ github.event.repository.full_name }}: build setup error'
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}
      - name: Prevent sending other notifications after this
        if: ${{ failure() && !env.DISCORD_NOTIFY_SENT }}
        run: |
          echo "DISCORD_NOTIFY_SENT=true" >> "$GITHUB_ENV"
      - name: Check style
        run: npm run eslint
      - name: Notify eslint error
        # if: ${{ failure() && !env.DISCORD_NOTIFY_SENT }}
        if: ${{ job.status != 'success' && !env.DISCORD_NOTIFY_SENT }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: error
          description: Eslint error
          details: 'Unable to proceed with testing and building commit: ${{ env.COMMIT_BASE_URL }}/${{ env.COMMIT_SHA }} by ${{ github.actor }}'
          text: '${{ github.event.repository.full_name }}: eslint error'
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}
      - name: Build
        run: npm run build
      - name: Notify build error
        if: ${{ failure() && !env.DISCORD_NOTIFY_SENT }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: error
          description: Build error
          details: 'Unable to proceed with tests and deployment of commit: ${{ env.COMMIT_BASE_URL }}/${{ env.COMMIT_SHA }} by ${{ github.actor }}'
          text: '${{ github.event.repository.full_name }}: build error'
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}
      - name: Run tests
        run: npm run test
      - name: Notify jest tests error
        if: ${{ failure() && !env.DISCORD_NOTIFY_SENT }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: error
          description: Test error
          details: 'Unable to proceed with e2e tests and deploying commit: ${{ env.COMMIT_BASE_URL }}/${{ env.COMMIT_SHA }} by ${{ github.actor }}'
          text: '${{ github.event.repository.full_name }}: test error'
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}
      - name: E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Notify e2e test error
        if: ${{ failure() && !env.DISCORD_NOTIFY_SENT }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: error
          description: E2E tests error
          details: 'E2E tests failed commit: ${{ env.COMMIT_BASE_URL }}/${{ env.COMMIT_SHA }} by ${{ github.actor }}'
          text: '${{ github.event.repository.full_name }}: test error'
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}
      - run: echo ${{ toJson(github.event.commits) }}
      - name: Notify succesfull build and test action
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
          severity: info
          description: Build and test action succesfull
          details: 'The commit ${{ env.COMMIT_BASE_URL }}/${{ env.COMMIT_SHA }} passed the tests!'
          text: '${{ github.event.repository.full_name }}: test & build success!'
          webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}
  deploy_to_render:
    name: Deploy to Render
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    runs-on: ubuntu-latest
    needs: simple_deployment_pipeline
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/render-deploy
        with:
          render-service-id: ${{ secrets.RENDER_SERVICE_ID }}
          render-api-key: ${{ secrets.RENDER_API_KEY }}
      # - name: Notify succesfull deployment action
      #   if: ${{ success() }}
      #   uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
      #   with:
      #     severity: info
      #     description: Deployment action succesfull
      #     details: 'Deployed to render.com: URL'
      #     text: A new version of Pokédex sent to render.com by ${{ github.actor }}
      #     webhookUrl: ${{ secrets.OMA_DISCORD_WEBHOOK }}
  tag_release:
    name: Bumb the version number (tag)
    needs: [simple_deployment_pipeline, deploy_to_render]
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Bumb version and push tag
        #https://github.com/anothrNick/github-tag-action/commit/a2c70ae13a881faf2b4953baaa9e49731997ab36
        # v1.67.0
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
