name: Testing stuff

on:
  push:
    branches:
      - master
      - 'Ex11.16-testing-2'
  # pull_request:
  # branches: [master]
  # types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages array
        env:
          COMMIT_MESSAGES_ARRAY: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "$COMMIT_MESSAGES_ARRAY"
      - name: 'check contains #skip'
        env:
          SKIP_CHECK: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: echo Commit messages contain \#skip:$SKIP_CHECK
